version: '3'
services:
  jenkins:
    image: istresearch/jenkins:latest
    container_name: jenkins
    user: jenkins
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"