version: '3'

services:
  postgres:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes: 
        - /c/dev/tools/docker_volumes/postgres:/data/postgres
    restart: unless-stopped
