version: "3"
services:
  sqlserver:
    container_name: sqlserver
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    volumes:
      - /home/otaviolarrosa/dev/tools/docker_volumes/sqlserver:/var/opt/mssql
    environment:
      SA_PASSWORD: "SQL.Server!2020"
      ACCEPT_EULA: "Y"
