version: "3"
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SQL.Server!2020"
      ACCEPT_EULA: "Y"

