version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - /c/dev/tools/docker_volumes/mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: otaviolarrosa
      MONGO_INITDB_ROOT_PASSWORD: Mongo.DB2020!
    ports:
      - "27017:27017"